### ISSUE TITLE
Holoviews doesn't support dim?

### ISSUE THREAD

**Issue by bkbu** [pyviz-dev/blog#10]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-bb1b6fcc1479> in <module>()
      2 import pandas as pd
      3 import holoviews as hv
----> 4 from holoviews import dim, opts
      5 
      6 hv.extension('bokeh')

ImportError: cannot import name 'dim'

**Comment by jbednar** [comment]
This repo is for our blog postings. Issues with holoviews go to https://github.com/holoviz/holoviews, but in this case it sounds like a broken installation of some sort, which is probably best discussed at https://discourse.holoviz.org/ (listing the version of holoviews you are trying to use and how you installed it).
