### ISSUE TITLE
My panel 0.13 blog feedback

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz-dev/blog#12]
I'm reviewing https://blog.holoviz.org/panel_0.13.0.html

## Order according to priority

I would suggest updating the list to

- Events support for Vega pane
- New widgets including rich-text editor and JSON editor
- Major new features for the Tabulator widget:
- LaTeX (MathJax) rendering support in Markdown/HTML panes
- Ability to display notifications in toasts
- Ability to schedule recurring tasks globally
- An admin dashboard to allow you to monitor, debug and profile your applications
- Built-in threading to make you apps more performant
- Time to live on `pn.state.as_cached`
- Performance and Debugging user guide
- Customizable Auth error page
- Select groups and disabled options

Most important things on the top.

## Notifications example not working

```python
import panel as pn

pn.extension(sizing_mode="stretch_width")

pn.io.notifications.NotificationArea.demo()
```

![image](https://user-images.githubusercontent.com/42288570/162283795-8325f03d-332c-4fa6-a846-2b154958124f.png)

## Give some simple real-life examples when built-in threading is useful

"Note that this is only useful if the application code releases the GIL, i.e. performs I/O bound operations or invokes computations that themselves release the GIL."

The most common operations are 

- loading data from file or database. Will threading be useful?
- working with (Pandas) dataframes. Will threading be useful?

## Tabulator

Add .gifs otherwise people will not understand what this is.

## Vega Events

This should be huge to the Vega community. So I think its fair to really highlight and announce this as something special.

## Rich text and JSON editors

Again provide .gifs so users now what you are talking about.

## General

Small minimum reproducible code snippets make it easy for users to try out the features. But they need to produce something useful end to end. Not only indicate parts of an application.

**Comment by jbednar** [comment]
My vote is that Tabulator support is more important to highlight than Vega support; people making dashboards very, very often need solid table, while most Panel users are tied to a particular plotting library already and not impacted by Vega support (cool as it is).

**Comment by MarcSkovMadsen** [comment]
I believe that Tabulator is huge. At least it’s huge for me. But I have not felt the interest from a lot of users and I’m surprised.

**Comment by MarcSkovMadsen** [comment]
I think the thing about Tabulator and tables is that interactive plots just communicates more easily. But in practice at least in trading and finance where I work Tables are so important.
