### ISSUE TITLE
HoloViz Blog is not readable on Iphone

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz-dev/blog#9]
The holoviz blog is almost unreadable on my iPhone running safari.

I just tried to read the [Panel 0.8.0 announcement blog[(http://blog.holoviz.org/panel_0.8.0.html). And it overflows and looks like below.

![image](https://user-images.githubusercontent.com/42288570/73602243-e9d62280-4570-11ea-92b3-a87f5f7c83e3.png)

![image](https://user-images.githubusercontent.com/42288570/73602246-f9556b80-4570-11ea-8849-b5ef86c22461.png)

**Comment by philippjfr** [comment]
This was fixed a little while back.
